### ISSUE TITLE
Google scrap - socket hang up

### ISSUE THREAD

**Issue by Sn0wFox** [if-h4102/man-manga#1]
I'm trying to build ManManga's search pipeline. However, the first step (google search) fails:
I'm calling (server side) `async function query(query: string): Promise<Item[]>` in the file `googlesearch.ts`, resulting in:

> socket hang up: undefined.

(throw line 98 of the node-google file)

However, i can make it work here: https://runkit.com/5858317b5cc1f70013c048f9/5858328b558ed60013d29208.
Any idea ?

**Comment by Sn0wFox** [comment]
I temporary fixed it using another scraping lib: https://www.npmjs.com/package/google-scraper.
But it can only retrieve links - no snippets nor title.

**Comment by demurgos** [comment]
Ok, I'll take a look at it. I was not really confident with the library we had so I'll check this one too.

**Comment by demurgos** [comment]
This is fixed in https://github.com/if-h4102/man-manga/commit/19893097cc98c7cf8225cc230a5aa4da53f22925.

I am working on the merge with master.
