### ISSUE TITLE
Spotlight doesn't work as intended

### ISSUE THREAD

**Issue by Sn0wFox** [if-h4102/man-manga#2]
It turns out that at the moment, spotlight doesn't work as intended: it's unable to find dbpedia resources from _several_ words. Example that you can reproduce on the branch `pipeline`:

```
git pull && git checkout pipeline
npm install
gulp client:build && gulp server:build
node build/server/server/main.js
GET http://localhost:3000/api/pipeline/tokyo ghoul (in your favorite browser)
```

You'll then see in the console where you launched the server all the steps of our pipeline. **But in the end, spotlight will find resources for _Tokyo_, for _Ghoul_, but not for _Tokyo Ghoul_.** And of course, the most important resource, http://dbpedia.org/resource/Tokyo_Ghoul won't be in the list, even with a confidence level equals to 0.

**Comment by Sn0wFox** [comment]
Maybe there's something to do with the parameter `spotter`.

**Comment by anliec** [comment]
first gulp command is unknown on my system...
then it's not a bug... spotlight prefer Tokyo and Ghoul than Tokyo Ghoul, it's a choice, after all it's not build for manga but for general subject.

**Comment by Sn0wFox** [comment]
> first gulp command is unknown on my system

`npm install -g gulp`

By the way, how have you build the project until now ? :octocat: 

> after all it's not build for manga but for general subject

Yup, that's one of my concern in #3. It's an awesome tool, but maybe it's doing a bit too much work that what we need.

**Comment by anliec** [comment]
> By the way, how have you build the project until now ? :octocat:
never say I've done so ;)
I tried, but found no way to install gulp... I suposed that gulp was suposed to install by himself during npm install. (you forgot to say that `npm install -g gulp` need administrator right to work correctly...)

> Yup, that's one of my concern in #3. It's an awesome tool, but maybe it's doing a bit too much work that what we need.
maybe not too much but not focused on the right direction...
