### ISSUE TITLE
Angular event and double way bindings are not working

### ISSUE THREAD

**Issue by Sn0wFox** [if-h4102/man-manga#5]
On branch `dynamic-component`:

The component search-bar component's template looks like this:

```pug
// Some divs ...
div
  input#search-field.input([(ngModel)]="query")
div
  button#search-button.waves-effect.waves-light.btn((click)="search()") Search
```

The `search() ` method looks like this:
```js
protected search(): void {
    console.log("SEARCHING");
    // API call
}
```

No errors are thrown, neither at run time or during build. But the `console.log("SEARCHING");` never happen, and neither do the API call. I believe that this comes from Angular Universal; and it's clearly harmful.

**Comment by Sn0wFox** [comment]
I tried it with https://github.com/angular/universal-starter.

**Comment by demurgos** [comment]
Seems to work on master, I'm rebasing this branch.

**Comment by Sn0wFox** [comment]
Ok. This has a high priority, thanks for managing it as quickly as possible.

**Comment by demurgos** [comment]
Fixed on the branch `rebased-dynamic-component`.

**Comment by Sn0wFox** [comment]
Nothing is fixed. Huge stack trace remains server and client side.

**Comment by demurgos** [comment]
Could you describe it ?
Does the errors happens when you load the page or when you click on the button ? Do you write a special query ? What is the complete error message ?

I was able to enter a query ("goku"), click on the button, log a message and then log the server's results.

**Comment by Sn0wFox** [comment]
On loading `localhost:3000`,
* Client side:
```
Unhandled Promise rejection: Failed to load /app.component.html ; Zone: <root> ; Task: Promise.then ; Value: Failed to load /app.component.html undefined

12:27:56,250 Error: Uncaught (in promise): Failed to load /app.component.html
Trace de la pile :
resolvePromise@http://localhost:3000/main.js:92193:31
resolvePromise@http://localhost:3000/main.js:92178:17
scheduleResolveOrReject/<@http://localhost:3000/main.js:92227:17
Zone$1</ZoneDelegate</ZoneDelegate.prototype.invokeTask@http://localhost:3000/main.js:91990:21
Zone$1</Zone</Zone.prototype.runTask@http://localhost:3000/main.js:91879:28
drainMicroTaskQueue@http://localhost:3000/main.js:92126:25
ZoneTask/this.invoke@http://localhost:3000/main.js:92064:25
 1 main.js:92115:9
	consoleError http://localhost:3000/main.js:92115:9
	drainMicroTaskQueue/_loop_1 http://localhost:3000/main.js:92142:25
	drainMicroTaskQueue http://localhost:3000/main.js:92146:21
	ZoneTask/this.invoke http://localhost:3000/main.js:92064:25
```

* Serveur side:
See [this gist](https://gist.github.com/Sn0wFox/7d12d715bdf71c023d49f925c9ba6c4a).

Nothing happens when trying to query something, as explained in the original issue.
Happens on branches `master` and `rebased-dynamic-component`.
Reproduce it (I did it):
```
git clone https://github.com/if-h4102/man-manga.git
cd man-manga
npm install
gulp all:clean-build
node build/server/server/main.js
```

**Comment by demurgos** [comment]
It should be fixed, make sure to upgrade the dependencies (`npm upgrade`). There was an error when bundling the client with webpack on Windows (with include rules for modules depending on the system separator).
The `html` and `css` files where not bundled leading to missing references and requests to non-existing files.
