### ISSUE TITLE
Add morgan logger

### ISSUE THREAD

**Issue by demurgos** [if-h4102/man-manga#8]
Log the requests to server with [Morgan](https://github.com/expressjs/morgan).

**Comment by Sn0wFox** [comment]
I was thinking about [winston](https://www.npmjs.com/package/winston), but i guess morgan will be just as fine. I'll assign someone.

**Comment by demurgos** [comment]
Morgan is a logger for express requests, winston looks more like a general purpose advanced logger.

I think they can be used together. Morgan can be a good start, it's just a few lines at the top of `server/main.ts` (does not require to change anything else).

**Comment by Sn0wFox** [comment]
Depends of what we need. At first Morgan will probably be enough. @anliec will deal with it as he intends.
